const cityInput=document.getElementById('cityInput'),searchBtn=document.getElementById('searchBtn'),locBtn=document.getElementById('locBtn'),cityNameEl=document.getElementById('cityName'),tempEl=document.getElementById('temp'),wIconEl=document.getElementById('wIcon'),descEl=document.getElementById('desc'),humidityEl=document.getElementById('humidity'),windEl=document.getElementById('wind'),feelsEl=document.getElementById('feels'),conditionEl=document.getElementById('condition'),dateTimeEl=document.getElementById('dateTime'),weatherCard=document.getElementById('weatherCard'),forecast=document.getElementById('forecast'),forecastGrid=document.getElementById('forecastGrid'),loader=document.getElementById('loader'),errorEl=document.getElementById('error');
const weatherCodes={0:{d:'Clear sky',i:'☀️'},1:{d:'Mainly clear',i:'🌤️'},2:{d:'Partly cloudy',i:'⛅'},3:{d:'Overcast',i:'☁️'},45:{d:'Fog',i:'🌫️'},48:{d:'Rime fog',i:'🌫️'},51:{d:'Light drizzle',i:'🌧️'},53:{d:'Drizzle',i:'🌧️'},55:{d:'Dense drizzle',i:'🌧️'},61:{d:'Slight rain',i:'🌦️'},63:{d:'Moderate rain',i:'🌧️'},65:{d:'Heavy rain',i:'🌧️'},71:{d:'Slight snow',i:'❄️'},73:{d:'Moderate snow',i:'❄️'},75:{d:'Heavy snow',i:'❄️'},80:{d:'Slight showers',i:'🌦️'},81:{d:'Moderate showers',i:'🌧️'},82:{d:'Violent showers',i:'⛈️'},95:{d:'Thunderstorm',i:'⛈️'},96:{d:'Thunderstorm hail',i:'⛈️'},99:{d:'Thunderstorm hail',i:'⛈️'}};
function showLoader(v){loader.classList.toggle('hidden',!v)}
function showError(msg){errorEl.textContent=msg;errorEl.classList.remove('hidden');setTimeout(()=>errorEl.classList.add('hidden'),4000)}
function formatDate(d){return new Date(d).toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'})}
async function getCoords(city){const res=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(city)}&count=1&language=en&format=json`);const data=await res.json();if(!data.results||data.results.length===0)throw new Error('City not found. Try Kampala, Nairobi, London');const r=data.results[0];return{lat:r.latitude,lon:r.longitude,name:`${r.name}, ${r.country}`}}
async function getWeather(lat,lon){const url=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m&daily=weather_code,temperature_2m_max,temperature_2m_min&timezone=auto`;const res=await fetch(url);return await res.json()}
async function searchCity(city){try{showLoader(true);errorEl.classList.add('hidden');const coords=await getCoords(city);const weather=await getWeather(coords.lat,coords.lon);const cur=weather.current;const code=weatherCodes[cur.weather_code]||{d:'Unknown',i:'⛅'};cityNameEl.textContent=coords.name;tempEl.textContent=Math.round(cur.temperature_2m)+'°C';wIconEl.textContent=code.i;descEl.textContent=code.d;humidityEl.textContent=cur.relative_humidity_2m+'%';windEl.textContent=cur.wind_speed_10m+' km/h';feelsEl.textContent=Math.round(cur.apparent_temperature)+'°C';conditionEl.textContent=code.d;dateTimeEl.textContent=new Date().toLocaleString('en-US',{weekday:'long',year:'numeric',month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'})+' | Lat:'+coords.lat.toFixed(2);forecastGrid.innerHTML='';const daily=weather.daily;for(let i=0;i<Math.min(7,daily.time.length);i++){const dCode=weatherCodes[daily.weather_code[i]]||{d:'',i:'⛅'};const div=document.createElement('div');div.className='day';div.innerHTML=`<div class="d-name">${i===0?'Today':formatDate(daily.time[i])}</div><div class="d-icon">${dCode.i}</div><div class="d-temp">${Math.round(daily.temperature_2m_max[i])}° / ${Math.round(daily.temperature_2m_min[i])}°</div><div class="d-min">${dCode.d}</div>`;forecastGrid.appendChild(div)}const isNight=new Date().getHours()<6||new Date().getHours()>18;if(cur.weather_code>=60)document.body.style.background='linear-gradient(135deg,#4b6cb7 0%,#182848 100%)';else if(cur.weather_code===0&&!isNight)document.body.style.background='linear-gradient(135deg,#f6d365 0%,#fda085 100%)';else if(isNight)document.body.style.background='linear-gradient(135deg,#141e30 0%,#243b55 100%)';else document.body.style.background='linear-gradient(135deg,#667eea 0%,#764ba2 100%)';weatherCard.classList.remove('hidden');forecast.classList.remove('hidden')}catch(e){showError(e.message);console.error(e)}finally{showLoader(false)}}
searchBtn.addEventListener('click',()=>{const c=cityInput.value.trim();if(c)searchCity(c)});
cityInput.addEventListener('keypress',(e)=>{if(e.key==='Enter'){const c=cityInput.value.trim();if(c)searchCity(c)}});
locBtn.addEventListener('click',()=>{if(!navigator.geolocation)return showError('Geolocation not supported');showLoader(true);navigator.geolocation.getCurrentPosition(async(pos)=>{try{const lat=pos.coords.latitude,lon=pos.coords.longitude;const weather=await getWeather(lat,lon);cityNameEl.textContent=`My Location (${lat.toFixed(2)}, ${lon.toFixed(2)})`;const cur=weather.current;const code=weatherCodes[cur.weather_code]||{d:'Unknown',i:'⛅'};tempEl.textContent=Math.round(cur.temperature_2m)+'°C';wIconEl.textContent=code.i;descEl.textContent=code.d;humidityEl.textContent=cur.relative_humidity_2m+'%';windEl.textContent=cur.wind_speed_10m+' km/h';feelsEl.textContent=Math.round(cur.apparent_temperature)+'°C';conditionEl.textContent=code.d;dateTimeEl.textContent=new Date().toLocaleString();forecastGrid.innerHTML='';for(let i=0;i<7;i++){const dCode=weatherCodes[weather.daily.weather_code[i]]||{d:'',i:'⛅'};const div=document.createElement('div');div.className='day';div.innerHTML=`<div class="d-name">${i===0?'Today':formatDate(weather.daily.time[i])}</div><div class="d-icon">${dCode.i}</div><div class="d-temp">${Math.round(weather.daily.temperature_2m_max[i])}° / ${Math.round(weather.daily.temperature_2m_min[i])}°</div>`;forecastGrid.appendChild(div)}weatherCard.classList.remove('hidden');forecast.classList.remove('hidden')}catch(e){showError(e.message)}finally{showLoader(false)}},()=>{showLoader(false);showError('Location permission denied')})});
searchCity('Kampala');
